version: "3.8"

services:
  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/sentiment
    depends_on:
      - backend

  backend:
    build:
      context: ./web/backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./web/backend/.cache:/app/.cache
